version: '3.3'
services:
  app:
    image: phatnguyen1812/golden-owl-test
    ports:
      - "3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
