name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types: 
      - completed

jobs:
  deploy-to-ec2:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull phatnguyen1812/golden-owl-test:latest

    - name: Change directory to src
      run: cd src

    - name: Run docker-compose
      run: |
        sudo docker-compose down || true
        sudo docker-compose up -d
      working-directory: ./

    

