name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types: 
      - completed

jobs:
  deploy-to-ec2:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull phatnguyen1812/golden-owl-test:latest

    - name: Delete old docker container (if existed)
      run: docker rm -f my-nodejs-app || true

    - name: Run docker container
      run: docker run -d -p 3000:3000 --name my-nodejs-app phatnguyen1812/golden-owl-test

    

