name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types: 
      - completed

jobs:
  deploy-to-ec2:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Pull Docker image
      run: docker pull phatnguyen1812/golden-owl-test:latest

    - name: Set docker-compose down
      working-directory: src
      run:
        docker-compose down || true

    - name: Run docker-compose
      working-directory: src
      run:
        docker-compose up -d

    

