name: Golden owl test CD/CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install required dependencies
      run: cd src & npm install

    - name: Run the tests
      run: cd src && npm test

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
  
      - name: Build the Docker image
        run: docker build -f src/Dockerfile --tag phatnguyen1812/golden-owl-test:tagname:latest
        if: ${{ steps.test.outputs.result == 'success' }}
    
      - name: Push the Docker image into dockerhub
        run: docker push phatnguyen1812/golden-owl-test:tagname:latest
        if: ${{ steps.test.outputs.result == 'success' }}
